import mysql.connector
from openpyxl import Workbook
import smtplib 
from email.mime.multipart import MIMEMultipart 
from email.mime.text import MIMEText 
from email.mime.base import MIMEBase 
from email import encoders
#import pathlib
import os

def main():
    db = mysql.connector.connect(user='root', password='root', host='localhost', db='traccar')
    cur= db.cursor()

    # Python list of dictionaries
    # More info at:
    #     https://stackoverflow.com/questions/8653516/python-list-of-dictionaries-search
    # Create Excel (.xlsx) file -----------------------------------------------
    wb = Workbook()

    #SQL = 'SELECT servertime,type,geofenceid FROM tc_events WHERE type=("geofenceEnter" AND "geofenceExit");'
    #S0 = 'alter table tc_events add (name varchar(20), geofence_name varchar(20))';
    #cur.execute(S0)
    S1 = 'update tc_events,tc_devices set tc_events.name = tc_devices.name where tc_events.deviceid = tc_devices.id';
    cur.execute(S1)
    S2= 'update tc_events,tc_geofences set tc_events.geofence_name = tc_geofences.name where tc_events.geofenceid = tc_geofences.id';
    cur.execute(S2)
     
    SQL = 'SELECT servertime,type,name,geofence_name FROM tc_events WHERE type=\'geofenceEnter\' OR type=\'geofenceExit\'';
    cur.execute(SQL)
    results = cur.fetchall()
    ws = wb.active
   # ws = wb.create_sheet(0)
   # ws.title = cars_table_name
    ws.append(cur.column_names)
    for row in results:
        ws.append(row)

    workbook_name = "test_workbook"
    wb.save(workbook_name + ".xlsx")

    fromaddr = "sender's address"
    toaddr = "receiver's address"

# instance of MIMEMultipart 
    msg = MIMEMultipart() 

# storing the senders email address 
    msg['From'] = fromaddr 

# storing the receivers email address 
    msg['To'] = toaddr 

# storing the subject 
    msg['Subject'] = "Visit Report"

# string to store the body of the mail 
    body = """Please find the 'Visit Report' attached below 
				Thank You
	(This mail is generated by server side program)
"""

# attach the body with the msg instance 
    msg.attach(MIMEText(body, 'plain')) 

# open the file to be sent 
    filename = "test_workbook.xlsx"
    a = os.path.join("/root/erpnext/", filename)
    attachment = open(a, "rb") 

# instance of MIMEBase and named as p 
    p = MIMEBase('application', 'octet-stream') 

# To change the payload into encoded form 
    p.set_payload((attachment).read()) 

# encode into base64 
    encoders.encode_base64(p) 

    p.add_header('Content-Disposition', "attachment; filename= %s" % filename) 

# attach the instance 'p' to instance 'msg' 
    msg.attach(p) 

# creates SMTP session 
    s = smtplib.SMTP('smtp.gmail.com', 587) 

# start TLS for security 
    s.starttls() 

# Authentication 
    s.login(fromaddr, "sender's pw") 

# Converts the Multipart msg into a string 
    text = msg.as_string() 

# sending the mail 
    s.sendmail(fromaddr, toaddr, text) 

# terminating the session 
    s.quit()

    print("Email sent successfully")

if  __name__ =='__main__':main() 

